apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secrets.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - api-pdb.yaml
  - web-deployment.yaml
  - web-service.yaml
  - web-hpa.yaml
  - web-pdb.yaml
  - worker-deployment.yaml
  - worker-hpa.yaml
  - worker-pdb.yaml
  - ingress.yaml
  - network-policies.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
