apiVersion: v1
kind: ConfigMap
metadata:
  name: smartbeak-config
data:
  NODE_ENV: "production"
  LOG_LEVEL: "debug"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4318"
  CACHE_VERSION: "v2"
  CACHE_PREFIX: "sb-staging"
